# .github/workflows/deploy-fly-dev.yml
name: Deploy to Fly.io Dev

on:
  push:
    branches:
      - deploy
  workflow_dispatch:
    inputs:
      version:
        description: "Image version to deploy (e.g. v1.2.3)"
        default: "latest"
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: "Image version to deploy (e.g. v1.2.3)"
        required: false
        default: "latest"
        type: string

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compute build date
        id: vars
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Resolve image tag
        id: set_tag
        run: echo "tag=${{ inputs.version || 'latest' }}" >> "$GITHUB_OUTPUT"

      # Create Fly.io app if it doesn't exist
      - name: Create App and Set Secrets
        run: |
          if ! flyctl apps list | grep -q petstore-grpc-dev; then
            flyctl apps create --name petstore-grpc-dev --auto-confirm
          else
            flyctl apps list
            echo "App petstore-grpc-dev already exists, skipping creation."
          fi

          flyctl secrets set --stage API_KEY=${{ secrets.API_KEY }} DATABASE_POOLER_URL=${{ secrets.DATABASE_POOLER_URL }} DATABASE_URL=${{ secrets.DATABASE_URL }} -c .fly/staging/fly.toml

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          flyctl deploy \
            --config .fly/dev/fly.toml \
            --image ghcr.io/ramonalcantaraarceo/petstore-grpc:${{ steps.set_tag.outputs.tag }} \
            --remote-only \
            --env GIT_SHA=${{ github.sha }} \
            --env BUILD_DATE=${{ steps.vars.outputs.date }} \
            --env VERSION=${{ steps.set_tag.outputs.tag }} \
            --debug \
            --verbose

          flyctl scale count 1 -y -c .fly/staging/fly.toml

          if ! flyctl certs list -c .fly/staging/fly.toml | grep -q petstore-grpc-dev.ramon-alcantara.work; then
            flyctl certs create petstore-grpc-dev.ramon-alcantara.work --app petstore-grpc-dev

          else
            echo "App petstore-grpc-dev already has certificate defined, skipping creation."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}